# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: LetMeIn!
    ports:
      - "5432:5432"
    volumes:
      - todo-web-data:/var/lib/mysql
volumes:
  todo-web-data: